matrix:
  include:
    - language: elixir
      elixir:
      - 1.9
      services:
        - postgresql
      stages:
        - name: deploy
          if: branch=master
          before_script:
            - PGPASSWORD=postgres psql -c 'create database gigalixir_getting_started_test;' -U postgres
          script:
            - git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git
            - mix test && mix coveralls.travis && git push -f gigalixir HEAD:refs/heads/master
