-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GrokStore.Object.Item exposing (checked, id, listId, location, price, quantity, text)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import GrokStore.InputObject
import GrokStore.Interface
import GrokStore.Object
import GrokStore.Scalar
import GrokStore.ScalarCodecs
import GrokStore.Union
import Json.Decode as Decode


checked : SelectionSet (Maybe Bool) GrokStore.Object.Item
checked =
    Object.selectionForField "(Maybe Bool)" "checked" [] (Decode.bool |> Decode.nullable)


id : SelectionSet (Maybe GrokStore.ScalarCodecs.Id) GrokStore.Object.Item
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (GrokStore.ScalarCodecs.codecs |> GrokStore.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


listId : SelectionSet (Maybe GrokStore.ScalarCodecs.Id) GrokStore.Object.Item
listId =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "listId" [] (GrokStore.ScalarCodecs.codecs |> GrokStore.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


location : SelectionSet (Maybe String) GrokStore.Object.Item
location =
    Object.selectionForField "(Maybe String)" "location" [] (Decode.string |> Decode.nullable)


price : SelectionSet (Maybe Float) GrokStore.Object.Item
price =
    Object.selectionForField "(Maybe Float)" "price" [] (Decode.float |> Decode.nullable)


quantity : SelectionSet (Maybe Int) GrokStore.Object.Item
quantity =
    Object.selectionForField "(Maybe Int)" "quantity" [] (Decode.int |> Decode.nullable)


text : SelectionSet (Maybe String) GrokStore.Object.Item
text =
    Object.selectionForField "(Maybe String)" "text" [] (Decode.string |> Decode.nullable)
