-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GrokStore.Object exposing (..)


type GrokList
    = GrokList


type Item
    = Item


type Session
    = Session


type User
    = User
