-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GrokStore.Object exposing (Item(..), List(..), Session(..), User(..))


type Item
    = Item


type List
    = List


type Session
    = Session


type User
    = User
